### ISSUE TITLE
RegistrationFailVadimTest: No newline at end of file

### ISSUE THREAD

**Issue by yurisv** [nokunev/testing-school-automation-week#1]
STEPS TO REPRODUCE:
1. Click on 'Commits' button
2. Choose commit "ad4a9f010ef1beb6e25c1177577625c06975484c"
3. Find file "RegistrationFailVadimTest.java"
4. Scroll down to the end of file

OBSERVED:
Error with text "No newline at end of file"

EXPECTED:
No error

**Comment by crossblade** [comment]
Fixed!
